// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(PersonsDbContext))]
    [Migration("20260906190749_tin_updated")]
    partial class tin_updated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryID");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryID = new Guid("69201c23-589b-45f3-88a7-97ef4de0bc66"),
                            CountryName = "Georgia"
                        },
                        new
                        {
                            CountryID = new Guid("ec5fea9a-76d9-4ce6-afa3-8eac27c3caab"),
                            CountryName = "Germany"
                        },
                        new
                        {
                            CountryID = new Guid("fa2d98af-fb39-4d22-ba2e-c4f01b3f50da"),
                            CountryName = "France"
                        },
                        new
                        {
                            CountryID = new Guid("b55de8fd-9c27-4860-8c43-443bbd0151d1"),
                            CountryName = "Japan"
                        },
                        new
                        {
                            CountryID = new Guid("fc08ff13-3464-40ed-862f-d83a9a1063a4"),
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryID = new Guid("44e36eb2-c1d9-42a3-8676-451c04e47f79"),
                            CountryName = "Brazil"
                        },
                        new
                        {
                            CountryID = new Guid("d801c7eb-bfa6-46b2-83dd-9a6afdb9028c"),
                            CountryName = "Australia"
                        },
                        new
                        {
                            CountryID = new Guid("8fbd2d4a-ef69-41ad-8d99-aa947eae5e85"),
                            CountryName = "Italy"
                        },
                        new
                        {
                            CountryID = new Guid("30118c4e-f405-41ed-9634-540ca02c446f"),
                            CountryName = "Spain"
                        },
                        new
                        {
                            CountryID = new Guid("268690d6-f1de-4cc8-bc53-5f3d254f7220"),
                            CountryName = "Norway"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Gender")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool?>("ReceiveNewsLetters")
                        .HasColumnType("bit");

                    b.Property<string>("TIN")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("TaxIdentificationNumber");

                    b.HasKey("PersonID");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonID = new Guid("3b5c4b23-de5a-4c58-a6e9-3318d8c85a6d"),
                            Address = "108 Lake Street",
                            CountryID = new Guid("30118c4e-f405-41ed-9634-540ca02c446f"),
                            DateOfBirth = new DateTime(1980, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "arthur.cooper0@outlook.com",
                            Gender = "Female",
                            PersonName = "Arthur",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("142fa1ca-7bf0-400b-b714-0d1b977308b1"),
                            Address = "605 Hill Avenue",
                            CountryID = new Guid("69201c23-589b-45f3-88a7-97ef4de0bc66"),
                            DateOfBirth = new DateTime(1979, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ethan.wilson1@example.com",
                            Gender = "Male",
                            PersonName = "Ethan",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("21690135-0ca3-40aa-b5f9-48766c6b3299"),
                            Address = "127 Main Way",
                            CountryID = new Guid("d801c7eb-bfa6-46b2-83dd-9a6afdb9028c"),
                            DateOfBirth = new DateTime(1979, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eva.brooks2@example.com",
                            Gender = "Female",
                            PersonName = "Eva",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("d2576ac4-1fbd-4e87-8bb3-077d90e9417f"),
                            Address = "526 Lake Way",
                            CountryID = new Guid("ec5fea9a-76d9-4ce6-afa3-8eac27c3caab"),
                            DateOfBirth = new DateTime(1979, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "arthur.carter3@example.com",
                            Gender = "Male",
                            PersonName = "Arthur",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("1a7be9e7-4325-447f-890c-01a137d2e14b"),
                            Address = "416 Park Road",
                            CountryID = new Guid("ec5fea9a-76d9-4ce6-afa3-8eac27c3caab"),
                            DateOfBirth = new DateTime(1995, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "oliver.turner4@example.com",
                            Gender = "Male",
                            PersonName = "Oliver",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("0e36435d-79aa-4d4b-8d88-9d060b28589c"),
                            Address = "509 Hill Drive",
                            CountryID = new Guid("30118c4e-f405-41ed-9634-540ca02c446f"),
                            DateOfBirth = new DateTime(1981, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maya.wilson5@mailbox.org",
                            Gender = "Female",
                            PersonName = "Maya",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("359a593e-e027-43c7-a9da-512b4d384ed5"),
                            Address = "809 Main Street",
                            CountryID = new Guid("ec5fea9a-76d9-4ce6-afa3-8eac27c3caab"),
                            DateOfBirth = new DateTime(1990, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "julia.parker6@example.com",
                            Gender = "Female",
                            PersonName = "Julia",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("0f471c8f-e4fb-40ce-b9c2-d223d8f44b8b"),
                            Address = "319 Main Street",
                            CountryID = new Guid("268690d6-f1de-4cc8-bc53-5f3d254f7220"),
                            DateOfBirth = new DateTime(1998, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.brooks7@proton.me",
                            Gender = "Male",
                            PersonName = "David",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("94d3006d-1235-4dba-9002-be4b54560083"),
                            Address = "290 River Street",
                            CountryID = new Guid("69201c23-589b-45f3-88a7-97ef4de0bc66"),
                            DateOfBirth = new DateTime(1980, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "elena.bennett8@example.com",
                            Gender = "Male",
                            PersonName = "Elena",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("35c319c9-04f1-4fc2-a5f6-118310eb0634"),
                            Address = "412 Main Avenue",
                            CountryID = new Guid("268690d6-f1de-4cc8-bc53-5f3d254f7220"),
                            DateOfBirth = new DateTime(1981, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "noah.hayes9@example.com",
                            Gender = "Female",
                            PersonName = "Noah",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("9ba3d887-f6f7-40a7-8019-4f2ff1d2f492"),
                            Address = "407 Cedar Street",
                            CountryID = new Guid("b55de8fd-9c27-4860-8c43-443bbd0151d1"),
                            DateOfBirth = new DateTime(1988, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "daniel.cooper10@mailbox.org",
                            Gender = "Male",
                            PersonName = "Daniel",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("bc924452-ca1a-44ac-adce-38db5d2c3f2a"),
                            Address = "943 Cedar Circle",
                            CountryID = new Guid("fa2d98af-fb39-4d22-ba2e-c4f01b3f50da"),
                            DateOfBirth = new DateTime(2001, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nora.morgan11@sample.net",
                            Gender = "Female",
                            PersonName = "Nora",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("be35387e-e876-4821-a823-72701af61406"),
                            Address = "685 Main Drive",
                            CountryID = new Guid("69201c23-589b-45f3-88a7-97ef4de0bc66"),
                            DateOfBirth = new DateTime(1981, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alex.reed12@sample.net",
                            Gender = "Male",
                            PersonName = "Alex",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("20f1f287-764a-48e1-ad67-99ce44e5c235"),
                            Address = "246 Main Avenue",
                            CountryID = new Guid("268690d6-f1de-4cc8-bc53-5f3d254f7220"),
                            DateOfBirth = new DateTime(1988, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sofia.morgan13@outlook.com",
                            Gender = "Male",
                            PersonName = "Sofia",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("796b64c0-0246-4258-b6d7-b02b69dbf3e9"),
                            Address = "14 Main Way",
                            CountryID = new Guid("268690d6-f1de-4cc8-bc53-5f3d254f7220"),
                            DateOfBirth = new DateTime(1993, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucas.foster14@proton.me",
                            Gender = "Female",
                            PersonName = "Lucas",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("7574b888-f5c2-4de5-8018-25ef8a08f81a"),
                            Address = "307 Cedar Street",
                            CountryID = new Guid("fa2d98af-fb39-4d22-ba2e-c4f01b3f50da"),
                            DateOfBirth = new DateTime(1982, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alex.reed15@sample.net",
                            Gender = "Male",
                            PersonName = "Alex",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("e0762d0f-099d-4cad-8914-0a772e170fc4"),
                            Address = "93 River Street",
                            CountryID = new Guid("8fbd2d4a-ef69-41ad-8d99-aa947eae5e85"),
                            DateOfBirth = new DateTime(1988, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maya.foster16@proton.me",
                            Gender = "Female",
                            PersonName = "Maya",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("540e46cd-5333-4e6f-96e6-ff9165d878ac"),
                            Address = "718 Park Way",
                            CountryID = new Guid("69201c23-589b-45f3-88a7-97ef4de0bc66"),
                            DateOfBirth = new DateTime(1994, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "oliver.carter17@proton.me",
                            Gender = "Male",
                            PersonName = "Oliver",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("de8308b7-a16c-4960-afe2-be2d67b58974"),
                            Address = "891 River Road",
                            CountryID = new Guid("fc08ff13-3464-40ed-862f-d83a9a1063a4"),
                            DateOfBirth = new DateTime(1995, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "henry.brooks18@sample.net",
                            Gender = "Male",
                            PersonName = "Henry",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("4abed33c-243f-46f0-887b-06ef26bf4658"),
                            Address = "634 Hill Road",
                            CountryID = new Guid("69201c23-589b-45f3-88a7-97ef4de0bc66"),
                            DateOfBirth = new DateTime(2000, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "victor.turner19@example.com",
                            Gender = "Female",
                            PersonName = "Victor",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("36d8cbd1-36fa-467e-98a5-907fc21c2ef8"),
                            Address = "675 Main Street",
                            CountryID = new Guid("d801c7eb-bfa6-46b2-83dd-9a6afdb9028c"),
                            DateOfBirth = new DateTime(1989, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucas.carter20@outlook.com",
                            Gender = "Female",
                            PersonName = "Lucas",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("8b96c45e-5414-4f61-85c3-805948f5da2c"),
                            Address = "588 Cedar Circle",
                            CountryID = new Guid("fc08ff13-3464-40ed-862f-d83a9a1063a4"),
                            DateOfBirth = new DateTime(1981, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "clara.turner21@example.com",
                            Gender = "Female",
                            PersonName = "Clara",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("8546322a-964c-4dc1-a148-95df9a6eb551"),
                            Address = "707 Lake Circle",
                            CountryID = new Guid("8fbd2d4a-ef69-41ad-8d99-aa947eae5e85"),
                            DateOfBirth = new DateTime(1998, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "arthur.bennett22@proton.me",
                            Gender = "Male",
                            PersonName = "Arthur",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("ff13a68c-4fd0-41b3-8fd2-15a05303cdfb"),
                            Address = "682 Lake Street",
                            CountryID = new Guid("d801c7eb-bfa6-46b2-83dd-9a6afdb9028c"),
                            DateOfBirth = new DateTime(1991, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.bennett23@proton.me",
                            Gender = "Female",
                            PersonName = "David",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("fb90e3f9-99b8-4bc1-be75-8a23cfbc70c9"),
                            Address = "215 Hill Avenue",
                            CountryID = new Guid("fa2d98af-fb39-4d22-ba2e-c4f01b3f50da"),
                            DateOfBirth = new DateTime(2001, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "daniel.morgan24@proton.me",
                            Gender = "Male",
                            PersonName = "Daniel",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("a0be6b91-f5d1-4a8b-8885-43f33158e2ef"),
                            Address = "466 Lake Avenue",
                            CountryID = new Guid("fa2d98af-fb39-4d22-ba2e-c4f01b3f50da"),
                            DateOfBirth = new DateTime(1997, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "daniel.miller25@mailbox.org",
                            Gender = "Female",
                            PersonName = "Daniel",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("9bf95620-6f77-4e45-bd85-24d037eb7ede"),
                            Address = "449 Oak Road",
                            CountryID = new Guid("8fbd2d4a-ef69-41ad-8d99-aa947eae5e85"),
                            DateOfBirth = new DateTime(1988, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "victor.foster26@outlook.com",
                            Gender = "Female",
                            PersonName = "Victor",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("934a1f5e-d7cf-4a01-8835-00d067ef9eea"),
                            Address = "261 River Circle",
                            CountryID = new Guid("8fbd2d4a-ef69-41ad-8d99-aa947eae5e85"),
                            DateOfBirth = new DateTime(1987, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "noah.reed27@mailbox.org",
                            Gender = "Male",
                            PersonName = "Noah",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("b6fe77ea-96a6-42b9-a4de-f6a0759ae7a6"),
                            Address = "779 River Street",
                            CountryID = new Guid("30118c4e-f405-41ed-9634-540ca02c446f"),
                            DateOfBirth = new DateTime(1999, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "arthur.turner28@sample.net",
                            Gender = "Female",
                            PersonName = "Arthur",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("0cb42fe1-316a-452c-9446-c4af47861a2d"),
                            Address = "16 Cedar Way",
                            CountryID = new Guid("b55de8fd-9c27-4860-8c43-443bbd0151d1"),
                            DateOfBirth = new DateTime(2002, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "julia.wilson29@mailbox.org",
                            Gender = "Female",
                            PersonName = "Julia",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("3cda8351-2412-4b93-baad-cbcf1614d0be"),
                            Address = "159 Oak Avenue",
                            CountryID = new Guid("fa2d98af-fb39-4d22-ba2e-c4f01b3f50da"),
                            DateOfBirth = new DateTime(1999, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma.hayes30@mailbox.org",
                            Gender = "Male",
                            PersonName = "Emma",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("d983f139-62b2-4af5-b74b-576a18fb6d77"),
                            Address = "883 River Drive",
                            CountryID = new Guid("b55de8fd-9c27-4860-8c43-443bbd0151d1"),
                            DateOfBirth = new DateTime(1983, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucas.hayes31@outlook.com",
                            Gender = "Male",
                            PersonName = "Lucas",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("7f0f5968-038d-40d5-87d2-aabc964a5070"),
                            Address = "449 Oak Road",
                            CountryID = new Guid("d801c7eb-bfa6-46b2-83dd-9a6afdb9028c"),
                            DateOfBirth = new DateTime(2000, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "julia.carter32@sample.net",
                            Gender = "Female",
                            PersonName = "Julia",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("85dfdbd8-5655-4a9e-870d-e23a3ca3bbf2"),
                            Address = "59 Hill Way",
                            CountryID = new Guid("30118c4e-f405-41ed-9634-540ca02c446f"),
                            DateOfBirth = new DateTime(1999, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "henry.brooks33@mailbox.org",
                            Gender = "Male",
                            PersonName = "Henry",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("0d7c2bd1-a943-4ccf-a112-23774d2a1621"),
                            Address = "420 Main Street",
                            CountryID = new Guid("268690d6-f1de-4cc8-bc53-5f3d254f7220"),
                            DateOfBirth = new DateTime(1994, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "samuel.parker34@sample.net",
                            Gender = "Female",
                            PersonName = "Samuel",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("a3f8cdec-52ca-4897-82c4-643266c1aeeb"),
                            Address = "110 Cedar Circle",
                            CountryID = new Guid("30118c4e-f405-41ed-9634-540ca02c446f"),
                            DateOfBirth = new DateTime(1981, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nora.wilson35@outlook.com",
                            Gender = "Male",
                            PersonName = "Nora",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("30daf9c5-4cfa-4cd0-a3e6-10c7d1648a56"),
                            Address = "635 Cedar Road",
                            CountryID = new Guid("8fbd2d4a-ef69-41ad-8d99-aa947eae5e85"),
                            DateOfBirth = new DateTime(2002, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sofia.reed36@example.com",
                            Gender = "Male",
                            PersonName = "Sofia",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("d35d084b-555e-4e2d-a145-d84e02312d8a"),
                            Address = "988 Oak Drive",
                            CountryID = new Guid("44e36eb2-c1d9-42a3-8676-451c04e47f79"),
                            DateOfBirth = new DateTime(2001, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma.brooks37@sample.net",
                            Gender = "Male",
                            PersonName = "Emma",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("9fd96a82-3de6-42ac-8170-e8391aa30bd8"),
                            Address = "687 Garden Avenue",
                            CountryID = new Guid("44e36eb2-c1d9-42a3-8676-451c04e47f79"),
                            DateOfBirth = new DateTime(1983, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maya.parker38@example.com",
                            Gender = "Female",
                            PersonName = "Maya",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("2323792f-de16-42d0-a83e-701ef6ff956d"),
                            Address = "4 Hill Road",
                            CountryID = new Guid("268690d6-f1de-4cc8-bc53-5f3d254f7220"),
                            DateOfBirth = new DateTime(1985, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anna.miller39@example.com",
                            Gender = "Male",
                            PersonName = "Anna",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("90152fe6-dd08-46d2-a97a-7e6c786df209"),
                            Address = "618 Park Road",
                            CountryID = new Guid("44e36eb2-c1d9-42a3-8676-451c04e47f79"),
                            DateOfBirth = new DateTime(1985, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sofia.carter40@proton.me",
                            Gender = "Male",
                            PersonName = "Sofia",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("e27b9e04-b564-4dd7-9af5-76389744d5b0"),
                            Address = "866 Hill Street",
                            CountryID = new Guid("d801c7eb-bfa6-46b2-83dd-9a6afdb9028c"),
                            DateOfBirth = new DateTime(1988, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sofia.miller41@outlook.com",
                            Gender = "Male",
                            PersonName = "Sofia",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("fcba0b12-3ed3-4b2f-a02b-a7dfb2e465c1"),
                            Address = "988 River Road",
                            CountryID = new Guid("268690d6-f1de-4cc8-bc53-5f3d254f7220"),
                            DateOfBirth = new DateTime(1986, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mila.morgan42@mailbox.org",
                            Gender = "Female",
                            PersonName = "Mila",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("526f39e6-e78a-4180-9920-ad0e17fdc7bd"),
                            Address = "40 Lake Avenue",
                            CountryID = new Guid("fa2d98af-fb39-4d22-ba2e-c4f01b3f50da"),
                            DateOfBirth = new DateTime(1988, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "henry.parker43@mailbox.org",
                            Gender = "Male",
                            PersonName = "Henry",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("8f4dfb56-b095-4a26-b80c-2b3b19f664f2"),
                            Address = "571 Oak Way",
                            CountryID = new Guid("d801c7eb-bfa6-46b2-83dd-9a6afdb9028c"),
                            DateOfBirth = new DateTime(1999, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mila.morgan44@sample.net",
                            Gender = "Male",
                            PersonName = "Mila",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("6879d142-2c5e-4498-9059-1f130d799cf3"),
                            Address = "586 Cedar Way",
                            CountryID = new Guid("44e36eb2-c1d9-42a3-8676-451c04e47f79"),
                            DateOfBirth = new DateTime(1990, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "julia.hayes45@example.com",
                            Gender = "Female",
                            PersonName = "Julia",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("6c26f12f-93a6-4112-9ee5-dd491a0ebf03"),
                            Address = "504 Hill Circle",
                            CountryID = new Guid("8fbd2d4a-ef69-41ad-8d99-aa947eae5e85"),
                            DateOfBirth = new DateTime(1989, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma.morgan46@sample.net",
                            Gender = "Female",
                            PersonName = "Emma",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("1ab8adeb-84cb-4a8e-8514-76901c180f49"),
                            Address = "83 River Street",
                            CountryID = new Guid("fc08ff13-3464-40ed-862f-d83a9a1063a4"),
                            DateOfBirth = new DateTime(1983, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "victor.foster47@proton.me",
                            Gender = "Female",
                            PersonName = "Victor",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("6323b06e-1bf6-47ba-87dd-1c8f981ef966"),
                            Address = "163 Hill Avenue",
                            CountryID = new Guid("69201c23-589b-45f3-88a7-97ef4de0bc66"),
                            DateOfBirth = new DateTime(1990, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mila.turner48@sample.net",
                            Gender = "Male",
                            PersonName = "Mila",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("bcd560a3-3b3d-42d1-b337-4260939cc415"),
                            Address = "661 River Circle",
                            CountryID = new Guid("44e36eb2-c1d9-42a3-8676-451c04e47f79"),
                            DateOfBirth = new DateTime(1998, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucas.parker49@example.com",
                            Gender = "Female",
                            PersonName = "Lucas",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("5546019b-56f1-4062-86de-efb608eb2867"),
                            Address = "37 Park Street",
                            CountryID = new Guid("268690d6-f1de-4cc8-bc53-5f3d254f7220"),
                            DateOfBirth = new DateTime(1983, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mila.carter50@outlook.com",
                            Gender = "Male",
                            PersonName = "Mila",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("b6c80a40-c651-4375-8628-0c819c93dfc0"),
                            Address = "771 Garden Street",
                            CountryID = new Guid("30118c4e-f405-41ed-9634-540ca02c446f"),
                            DateOfBirth = new DateTime(1979, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mila.cooper51@sample.net",
                            Gender = "Male",
                            PersonName = "Mila",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("50269cc9-c416-4389-aaf6-2aee3b95266f"),
                            Address = "560 Park Road",
                            CountryID = new Guid("ec5fea9a-76d9-4ce6-afa3-8eac27c3caab"),
                            DateOfBirth = new DateTime(1986, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ethan.hayes52@mailbox.org",
                            Gender = "Female",
                            PersonName = "Ethan",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("0a00f0ca-eece-4783-810f-95de9a0e5fb8"),
                            Address = "939 Park Way",
                            CountryID = new Guid("ec5fea9a-76d9-4ce6-afa3-8eac27c3caab"),
                            DateOfBirth = new DateTime(1990, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eva.brooks53@example.com",
                            Gender = "Female",
                            PersonName = "Eva",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("9b4804ef-4cf5-4c72-9394-fe0a86dd6deb"),
                            Address = "766 River Circle",
                            CountryID = new Guid("30118c4e-f405-41ed-9634-540ca02c446f"),
                            DateOfBirth = new DateTime(1979, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mila.morgan54@outlook.com",
                            Gender = "Male",
                            PersonName = "Mila",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("c6f05580-8ba0-4379-8f0d-8d963f988ca2"),
                            Address = "250 Cedar Road",
                            CountryID = new Guid("fa2d98af-fb39-4d22-ba2e-c4f01b3f50da"),
                            DateOfBirth = new DateTime(1981, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "henry.morgan55@proton.me",
                            Gender = "Male",
                            PersonName = "Henry",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("29cd8ebc-7af2-49c3-be75-5f1097b37299"),
                            Address = "138 Oak Circle",
                            CountryID = new Guid("b55de8fd-9c27-4860-8c43-443bbd0151d1"),
                            DateOfBirth = new DateTime(1984, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ethan.brooks56@sample.net",
                            Gender = "Male",
                            PersonName = "Ethan",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("39d44177-39f0-4f48-ab55-71375935295f"),
                            Address = "688 Garden Drive",
                            CountryID = new Guid("b55de8fd-9c27-4860-8c43-443bbd0151d1"),
                            DateOfBirth = new DateTime(1978, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "noah.reed57@sample.net",
                            Gender = "Female",
                            PersonName = "Noah",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("aad09c55-d059-43ec-9b22-cff2fbbcd82d"),
                            Address = "353 Cedar Circle",
                            CountryID = new Guid("d801c7eb-bfa6-46b2-83dd-9a6afdb9028c"),
                            DateOfBirth = new DateTime(1983, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucas.parker58@proton.me",
                            Gender = "Female",
                            PersonName = "Lucas",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("244ed71b-1b2c-45c6-8522-7390fe2800f1"),
                            Address = "505 Main Street",
                            CountryID = new Guid("d801c7eb-bfa6-46b2-83dd-9a6afdb9028c"),
                            DateOfBirth = new DateTime(1979, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ethan.foster59@mailbox.org",
                            Gender = "Female",
                            PersonName = "Ethan",
                            ReceiveNewsLetters = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
